/-
  Cross-validation tests comparing our implementation with protoc output.

  These tests read binary files generated by protoc and verify that our
  decoder produces the correct values.
-/
import Protolean

namespace Tests.Integration

/-- Read a binary fixture file -/
def readFixture (name : String) : IO ByteArray := do
  let path := s!"Tests/Integration/fixtures/generated/{name}"
  IO.FS.readBinFile (System.FilePath.mk path)

/-- Test helper for checking decode results -/
def testDecode [Protolean.ProtoMessage α] [Repr α]
    (name : String) (bytes : ByteArray) (check : α → Bool) : IO Bool := do
  match Protolean.decodeMessage bytes with
  | .ok decoded =>
    if check decoded then
      IO.println s!"  PASS: {name}"
      return true
    else
      IO.println s!"  FAIL: {name} - decoded value did not match expected"
      IO.println s!"        Got: {repr decoded}"
      return false
  | .error e =>
    IO.println s!"  FAIL: {name} - decode error: {e}"
    return false

/-- Test encoding matches protoc output -/
def testEncode [Protolean.ProtoMessage α] [Repr α]
    (name : String) (value : α) (expected : ByteArray) : IO Bool := do
  let encoded := Protolean.encodeMessage value
  if encoded == expected then
    IO.println s!"  PASS: {name}"
    return true
  else
    IO.println s!"  FAIL: {name} - encoded bytes did not match"
    IO.println s!"        Expected {expected.size} bytes: {expected.toList}"
    IO.println s!"        Got {encoded.size} bytes: {encoded.toList}"
    return false

/-- Run cross-validation tests -/
def runTests : IO Unit := do
  IO.println "Running cross-validation tests..."
  IO.println "(Note: These tests require running scripts/generate_test_fixtures.sh first)"
  IO.println ""

  -- Check if fixtures exist
  let fixturesPath := System.FilePath.mk "Tests/Integration/fixtures/generated"
  let exists ← fixturesPath.pathExists
  if !exists then
    IO.println "Fixtures not found. Please run: ./scripts/generate_test_fixtures.sh"
    return

  IO.println "Cross-validation tests would go here."
  IO.println "Once we have the proto_import macro working, we can:"
  IO.println "1. Import test.proto"
  IO.println "2. Read the .bin fixtures"
  IO.println "3. Decode and verify the values"
  IO.println "4. Encode our own values and compare bytes"

end Tests.Integration
